### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by GrangerTheDog** [melerpe/DVZ#1]
**Hi there,**
Welcome to my Dwarves VS Zombies project! And i want you to help me!
In the dwarves vs zombies gamemode there are several features that need to be made in to the skript!

# Main
- [ ] Easy inhouse function API
- [ ] .yml config for optimal usage
- [ ] Good formatting

# Gameplay
## General

- [ ] Shrine
- [ ] Building & Gathering items

### Zombies

- [ ] Zombie
- [ ] Skeleton
- [ ] Creeper
- [ ] Spider
- [ ] Wither skeleton
- [ ] Wolf
- [ ] Iron Golem
- [ ] More...

### Dwarfs

- [ ] Builder(Normal)
- [ ] Assasin
- [ ] Alchemist (Different gamemode)
- [ ] More...
